Trying to add additional debug info on CI failure

diff --git a/.github/workflows/build-android.yml b/.github/workflows/build-android.yml
--- a/.github/workflows/build-android.yml
+++ b/.github/workflows/build-android.yml
@@ -43,7 +43,11 @@ jobs:
       
       - name: Verify alignment
         run: |
-          cd app/release
+          cd packages/app-mobile/android/app
+          if test ! -d ./release ; then
+            echo "Missing release folder."
+            exit 1
+          fi
           BUILD_TOOLS_PATH=$ANDROID_HOME/build-tools/
           if test ! -d "$BUILD_TOOLS_PATH" ; then
             echo "Build tools not found at $BUILD_TOOLS_PATH ($ANDROID_HOME, $BUILD_TOOLS_VERSION)"
