Attempt to check APK alignment in CI

diff --git a/.github/workflows/build-android.yml b/.github/workflows/build-android.yml
--- a/.github/workflows/build-android.yml
+++ b/.github/workflows/build-android.yml
@@ -40,4 +40,21 @@ jobs:
           cd packages/app-mobile/android
           sed -i -- 's/signingConfig signingConfigs.release/signingConfig signingConfigs.debug/' app/build.gradle
           ./gradlew assembleRelease
-          
+      
+      - name: Verify alignment
+        run: |
+          cd packages/app-mobile/android/app/release
+          BUILD_TOOLS_PATH=$ANDROID_HOME/build-tools/
+          if test ! -d "$BUILD_TOOLS_PATH" ; then
+            echo "Build tools not found at $BUILD_TOOLS_PATH ($ANDROID_HOME, $BUILD_TOOLS_VERSION)"
+            exit 1
+          fi
+          # The build-tools/ directory contains different subdirectories
+          # for each build tools version. As a result, there may be multiple
+          # zipalign tools. Select one of them:
+          ZIPALIGN_PATH=$(find $BUILD_TOOLS_PATH -name "zipalign" -print | head -n1)
+          if test ! -x "$ZIPALIGN_PATH" ; then
+            echo "zipalign not found (searching in $BUILD_TOOLS_PATH, candidate: $ZIPALIGN_PATH)"
+            exit 1
+          fi
+          $BUILD_TOOLS_PATH/zipalign -c -P 16 -v 4 ./app-release.apk
